[package]
name = "validator_change"
version = "0.1.0"
authors = ["Paul Hauner <paul@paulhauner.com>"]
edition = "2018"

[dependencies]
bytes = "0.4.10"
eth2_hashing = { path = "../utils/eth2_hashing" }
eth2_ssz = "0.1"
types = { path = "../types" }
