[package]
name = "slasher"
version = "0.1.0"
authors = ["Michael Sproul <michael@sigmaprime.io>"]
edition = "2018"

[dependencies]
bincode = "1.3.1"
byteorder = "1.3.4"
eth2_ssz = "0.4.0"
eth2_ssz_derive = "0.3.0"
flate2 = { version = "1.0.14", features = ["zlib"], default-features = false }
lazy_static = "1.4.0"
lighthouse_metrics = { path = "../common/lighthouse_metrics" }
filesystem = { path = "../common/filesystem" }
lmdb = "0.8"
lmdb-sys = "0.8"
parking_lot = "0.11.0"
rand = "0.7.3"
safe_arith = { path = "../consensus/safe_arith" }
serde = "1.0"
serde_derive = "1.0"
slog = "2.5.2"
sloggers = "2.0.2"
tree_hash = "0.4.0"
tree_hash_derive = "0.4.0"
types = { path = "../consensus/types" }

[dev-dependencies]
maplit = "1.0.2"
rayon = "1.3.0"
tempfile = "3.1.0"
logging = { path = "../common/logging" }

