[package]
name = "slasher"
version = "0.1.0"
authors = ["Michael Sproul <michael@sigmaprime.io>"]
edition = "2018"

[dependencies]
bincode = "1.3.1"
blake2b_simd = "0.5.10"
byte-slice-cast = "0.3.5"
environment = { path = "../lighthouse/environment" }
eth2_ssz = { path = "../consensus/ssz" }
eth2_ssz_derive = { path = "../consensus/ssz_derive" }
flate2 = { version = "1.0.17", features = ["zlib"], default-features = false }
lmdb = "0.8"
parking_lot = "0.11.0"
rand = "0.7"
safe_arith = { path = "../consensus/safe_arith" }
serde = "1.0"
serde_derive = "1.0"
slog = "2.5.2"
slot_clock = { path = "../common/slot_clock" }
tokio = { version = "0.2.21", features = ["full"] }
tree_hash = { path = "../consensus/tree_hash" }
types = { path = "../consensus/types" }

[dev-dependencies]
criterion = "0.3"
rayon = "1.3.0"
slog-term = "2.6.0"
tempdir = "0.3.7"

[[bench]]
name = "blake2b"
harness = false
