[package]
name = "test_random_derive"
version = "0.1.0"
authors = ["thojest <thojest@gmail.com>"]
edition = "2018"
description = "Procedural derive macros for implementation of TestRandom trait"

[lib]
proc-macro = true

[dependencies]
syn = "0.15"
quote = "0.6"
