[package]
name = "eth2_wallet"
version = "0.1.0"
authors = ["Paul Hauner <paul@paulhauner.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.116"
serde_json = "1.0.58"
serde_repr = "0.1.6"
uuid = { version = "0.8.1", features = ["serde", "v4"] }
rand = "0.7.3"
eth2_keystore = { path = "../eth2_keystore" }
eth2_key_derivation = { path = "../eth2_key_derivation" }
tiny-bip39 = "0.8.1"

[dev-dependencies]
hex = "0.4.2"
tempfile = "3.1.0"
