[package]
name = "hashset_delay"
version = "0.2.0"
authors = ["Age Manning <Age@AgeManning.com>"]
edition = "2018"

[dependencies]
futures = "0.3.5"
tokio = { version = "0.2.21", features = ["time"] }

[dev-dependencies]
tokio = { version = "0.2.21", features = ["time", "rt-threaded", "macros"] }
