[package]
name = "hashset_delay"
version = "0.2.0"
authors = ["Sigma Prime <contact@sigmaprime.io>"]
edition = "2018"

[dependencies]
futures = "0.3.7"
tokio-util = { version = "0.6.2", features = ["time"] }

[dev-dependencies]
tokio = { version = "1.10.0", features = ["time", "rt-multi-thread", "macros"] }
