#Adapted from https://users.rust-lang.org/t/my-gitlab-config-docs-tests/16396

image: 'sigp/lighthouse:latest'

stages:
  - test
  - document

variables:
    CARGO_HOME: /cache/cargocache

check-fmt:
  stage: test
  script:
    - cargo build --manifest-path protos/Cargo.toml
    - cargo fmt --all -- --check

test-dev:
  stage: test
  variables:
    GIT_SUBMODULE_STRATEGY: normal
  script:
    - cargo test --verbose --all

test-release:
  stage: test
  variables:
    GIT_SUBMODULE_STRATEGY: normal
  script:
    - cargo test --verbose --all --release

test-fake-crypto:
  stage: test
  variables:
    GIT_SUBMODULE_STRATEGY: normal
  script:
    - cargo test --manifest-path tests/ef_tests/Cargo.toml --release --features fake_crypto

documentation:
  stage: document
  script:
    - cargo doc --no-deps
    - aws s3 sync target/doc/ s3://lighthouse-docs.sigmaprime.io/ --exclude '.lock' --delete
  # Configure the below when we want to have a default page (and update S3 bucket index).
  #    - echo '<meta http-equiv="refresh" content="0; url={{ LIBRARY NAME }}">' > public/index.html
  only:
    - master
