status = [
    "release-tests-ubuntu",
    "release-tests-windows",
    "debug-tests-ubuntu",
    "state-transition-vectors-ubuntu",
    "ef-tests-ubuntu",
    "dockerfile-ubuntu",
    "eth1-simulator-ubuntu",
    "merge-transition-ubuntu",
    "no-eth1-simulator-ubuntu",
    "check-code",
    "cargo-udeps",
    "beacon-chain-tests",
    "op-pool-tests",
    "doppelganger-protection-test",
    "execution-engine-integration-ubuntu",
    "check-msrv",
    "slasher-tests",
    "syncing-simulator-ubuntu",
    "compile-with-beta-compiler",
]
use_squash_merge = true
timeout_sec = 10800
pr_status = ["license/cla", "target-branch-check"]
