[package]
name = "eth2_ssz_types"
version = "0.2.0"
authors = ["Paul Hauner <paul@paulhauner.com>"]
edition = "2018"

[lib]
name = "ssz_types"

[dependencies]
tree_hash = "0.1"
serde = "1.0"
serde_derive = "1.0"
serde_hex = { path = "../serde_hex" }
eth2_ssz = "0.1"
typenum = "1.10"

[dev-dependencies]
serde_yaml = "0.8"
tree_hash_derive = "0.2"
