[package]
name = "beacon_chain_fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[features]
default = ["minimal"]
minimal = []
mainnet = []
afl = ["dep:afl"] # this feature enables the fuzzer
repro = [] # this feature enables the test-case reproducer

[package.metadata]
cargo-fuzz = true

[dependencies]
arbitrary = { version = "1.1.3", features = ["derive"] }
store = { path = "../../store" }
lazy_static = "1.4.0"
slog = { version = "2.5.2", features = ["max_level_trace"] }
sloggers = { version = "2.1.1", features = ["json"] }
state_processing = { path = "../../../consensus/state_processing" }
tree_hash = "0.5.0"
types = { path = "../../../consensus/types" }
rand = "0.8.5"
tempfile = "3.1.0"
fork_choice = { path = "../../../consensus/fork_choice" }
logging = { path = "../../../common/logging" }
tokio = { version = "1", features = ["rt-multi-thread"] }
bls = { path = "../../../crypto/bls" }
strum = "0.24.1"
async-recursion = "1.0.0"
parking_lot = "0.12.1"

afl = { version = "*", optional = true }

[dependencies.beacon_chain]
path = ".."
features = ["hydra"]

[[bin]]
name = "fuzzer"
path = "fuzz_targets/run.rs"
test = false
doc = false
required-features = ["afl"]

[[bin]]
name = "repro"
path = "fuzz_targets/repro.rs"
test = false
doc = false
required-features = ["repro"]
