[package]
name = "eth1_test_rig"
version = "0.2.0"
authors = ["Paul Hauner <paul@paulhauner.com>"]
edition = "2018"

[dependencies]
tokio = { version = "0.2.22", features = ["time"] }
web3 = "0.11.0"
futures = { version = "0.3.5", features = ["compat"] }
types = { path = "../../consensus/types"}
serde_json = "1.0.58"
deposit_contract = { path = "../../common/deposit_contract"}
