[package]
name = "eth2_testnet_config"
version = "0.2.0"
authors = ["Paul Hauner <paul@paulhauner.com>"]
edition = "2018"

build = "build.rs"

[build-dependencies]
reqwest = { version = "0.10.4", features = ["blocking"] }

[dev-dependencies]
tempdir = "0.3.7"

[dependencies]
serde = "1.0.110"
serde_yaml = "0.8.11"
types = { path = "../../consensus/types"}
enr = { version = "0.1.0", features = ["libsecp256k1", "ed25519"] }
eth2_ssz = "0.1.2"
