[package]
name = "eth2_testnet_config"
version = "0.2.0"
authors = ["Paul Hauner <paul@paulhauner.com>"]
edition = "2018"

build = "build.rs"

[build-dependencies]
zip = "0.5"
eth2_config = { path = "../eth2_config"}

[dev-dependencies]
tempdir = "0.3.7"

[dependencies]
serde = "1.0.110"
serde_yaml = "0.8.11"
types = { path = "../../consensus/types"}
#enr = { version = "0.1.0", features = ["libsecp256k1", "ed25519"] }
eth2_ssz = "0.1.2"
eth2_config = { path = "../eth2_config"}
eth2_libp2p = { path = "../../beacon_node/eth2_libp2p"}
