[package]
name = "compare_fields"
version = "0.2.0"
authors = ["Paul Hauner <paul@paulhauner.com>"]
edition = { workspace = true }

[dev-dependencies]
compare_fields_derive = { workspace = true }

[package.metadata.cargo-udeps.ignore]
development = ["compare_fields_derive"] # used in doc-tests
