[package]
name = "compare_fields"
version = "0.1.0"
authors = ["Paul Hauner <paul@paulhauner.com>"]
edition = "2018"

[dev-dependencies]
compare_fields_derive = { path = "../compare_fields_derive" }

[dependencies]
