[package]
name = "simulator"
version = "0.2.0"
authors = ["Paul Hauner <paul@paulhauner.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
node_test_rig = { path = "../node_test_rig" }
eth1 = {path = "../../beacon_node/eth1"}
types = { path = "../../consensus/types" }
parking_lot = "0.11.0"
futures = "0.3.7"
tokio = "1.10.0"
eth1_test_rig = { path = "../eth1_test_rig" }
env_logger = "0.9.0"
clap = "2.33.3"
rayon = "1.4.1"
sensitive_url  = { path = "../../common/sensitive_url" }
