[package]
name = "operation_pool"
version = "0.1.0"
authors = ["Michael Sproul <michael@sigmaprime.io>"]
edition = "2018"

[dependencies]
int_to_bytes = { path = "../utils/int_to_bytes" }
itertools = "0.8"
parking_lot = "0.7"
types = { path = "../types" }
state_processing = { path = "../state_processing" }
eth2_ssz = "0.1"
eth2_ssz_derive = { path = "../utils/ssz_derive" }

[dev-dependencies]
rand = "0.5.5"
