[package]
name = "eth2_config"
version = "0.2.0"
authors = ["Paul Hauner <paul@paulhauner.com>"]
edition = "2018"

[dependencies]
serde = "1.0.116"
serde_derive = "1.0.116"
toml = "0.5.6"
types = { path = "../../consensus/types" }
