[package]
name = "genesis"
version = "0.2.0"
authors = ["Paul Hauner <paul@paulhauner.com>"]
edition = "2018"

[dev-dependencies]
eth1_test_rig = { path = "../../testing/eth1_test_rig" }
sensitive_url = { path = "../../common/sensitive_url" }

[dependencies]
futures = "0.3.7"
types = { path = "../../consensus/types"}
environment = { path = "../../lighthouse/environment"}
eth1 = { path = "../eth1"}
rayon = "1.4.1"
state_processing = { path = "../../consensus/state_processing" }
merkle_proof = { path = "../../consensus/merkle_proof" }
eth2_ssz = "0.4.0"
eth2_hashing = "0.2.0"
tree_hash = "0.4.0"
tokio = { version = "1.10.0", features = ["full"] }
slog = "2.5.2"
int_to_bytes = { path = "../../consensus/int_to_bytes" }
