[package]
name = "boolean-bitfield"
version = "0.1.0"
authors = ["Paul Hauner <paul@paulhauner.com>"]
edition = "2018"

[dependencies]
serde_hex = { path = "../serde_hex" }
ssz = { path = "../ssz" }
bit-vec = "0.5.0"
bit_reverse = "0.1"
serde = "1.0"
serde_derive = "1.0"
tree_hash = { path = "../tree_hash" }

[dev-dependencies]
serde_yaml = "0.8"
