[package]
name = "genesis"
version = "0.1.0"
authors = ["Paul Hauner <paul@paulhauner.com>"]
edition = "2018"

[dependencies]
bls = { path = "../utils/bls"  }
ssz = { path = "../utils/ssz" }
types = { path = "../types"  }
validator_induction = { path = "../validator_induction"  }
validator_shuffling = { path = "../validator_shuffling"  }
