[package]
name = "int_to_bytes"
version = "0.2.0"
authors = ["Paul Hauner <paul@paulhauner.com>"]
edition = "2018"

[dependencies]
bytes = "0.5.4"

[dev-dependencies]
yaml-rust = "0.4.3"
hex = "0.4.2"
