[package]
name = "proto_array"
version = "0.2.0"
authors = ["Paul Hauner <paul@sigmaprime.io>"]
edition = { workspace = true }

[[bin]]
name = "proto_array"
path = "src/bin.rs"

[dependencies]
types = { workspace = true }
ethereum_ssz = { workspace = true }
ethereum_ssz_derive = { workspace = true }
serde = { workspace = true }
serde_derive = "1.0.116"
serde_yaml = { workspace = true }
safe_arith = { workspace = true }
superstruct = { workspace = true }