[package]
name = "swap_or_not_shuffle"
version = "0.1.0"
authors = ["Paul Hauner <paul@paulhauner.com>"]
edition = "2018"

[[bench]]
name = "benches"
harness = false

[dev-dependencies]
criterion = "0.3.0"
yaml-rust = "0.4.3"
hex = "0.3"
ethereum-types = "0.8.0"

[dependencies]
eth2_hashing = "0.1.0"
int_to_bytes = { path = "../int_to_bytes" }
