[package]
name = "swap_or_not_shuffle"
version = "0.1.0"
authors = ["Paul Hauner <paul@paulhauner.com>"]
edition = "2018"

[[bench]]
name = "benches"
harness = false

[dev-dependencies]
criterion = "0.2"
yaml-rust = "0.4.2"
hex = "0.3"
ethereum-types = "0.5"

[dependencies]
hashing = { path = "../hashing" }
int_to_bytes = { path = "../int_to_bytes" }
