[package]
name = "eth2_interop_keypairs"
version = "0.1.0"
authors = ["Paul Hauner <paul@paulhauner.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
num-bigint = "0.2.3"
eth2_hashing = "0.1.0"
hex = "0.3"
milagro_bls = { git = "https://github.com/sigp/milagro_bls", branch = "eth2.0-v0.10" }
serde_yaml = "0.8.11"
serde = "1.0.102"
serde_derive = "1.0.102"

[dev-dependencies]
base64 = "0.11.0"
