[package]
name = "eth2_ssz"
version = "0.4.0"
authors = ["Paul Hauner <paul@sigmaprime.io>"]
edition = "2018"
description = "SimpleSerialize (SSZ) as used in Ethereum 2.0"
license = "Apache-2.0"

[lib]
name = "ssz"

[dev-dependencies]
eth2_ssz_derive = "0.3.0"

[dependencies]
ethereum-types = "0.12.1"
smallvec = "1.6.1"

[features]
arbitrary = ["ethereum-types/arbitrary"]
