[package]
name = "state_processing"
version = "0.2.0"
authors = ["Paul Hauner <paul@paulhauner.com>"]
edition = "2018"

[[bench]]
name = "benches"
harness = false

[dev-dependencies]
criterion = "0.3.0"
env_logger = "0.7.1"
serde = "1.0.102"
serde_derive = "1.0.102"
lazy_static = "1.4.0"
serde_yaml = "0.8.11"
beacon_chain = { path = "../../beacon_node/beacon_chain" }
store = { path = "../../beacon_node/store" }


[dependencies]
bls = { path = "../utils/bls" }
integer-sqrt = "0.1.2"
itertools = "0.8.1"
eth2_ssz = "0.1.2"
eth2_ssz_types = { path = "../utils/ssz_types" }
merkle_proof = { path = "../utils/merkle_proof" }
log = "0.4.8"
safe_arith = { path = "../utils/safe_arith" }
tree_hash = "0.1.0"
tree_hash_derive = "0.2"
types = { path = "../types" }
rayon = "1.2.0"
eth2_hashing = { path = "../utils/eth2_hashing" }
int_to_bytes = { path = "../utils/int_to_bytes" }
arbitrary = { version = "0.4.3", features = ["derive"], optional = true }

[features]
fake_crypto = ["bls/fake_crypto"]
arbitrary-fuzz = [
  "arbitrary",
  "types/arbitrary-fuzz",
  "bls/arbitrary",
  "merkle_proof/arbitrary",
  "eth2_ssz/arbitrary",
  "eth2_ssz_types/arbitrary",
  "tree_hash/arbitrary",
]
