[package]
name = "operation_pool"
version = "0.2.0"
authors = ["Michael Sproul <michael@sigmaprime.io>"]
edition = { workspace = true }

[dependencies]
derivative = { workspace = true }
itertools = { workspace = true }
lazy_static = { workspace = true }
lighthouse_metrics = { workspace = true }
parking_lot = { workspace = true }
types = { workspace = true }
state_processing = { workspace = true }
ethereum_ssz = { workspace = true }
ethereum_ssz_derive = { workspace = true }
rayon = { workspace = true }
serde = { workspace = true }
serde_derive = "1.0.116"
store = { workspace = true }
bitvec = { workspace = true }
rand = { workspace = true }

[dev-dependencies]
beacon_chain = { workspace = true }
tokio = { workspace = true }
maplit = { workspace = true }
