[package]
name = "operation_pool"
version = "0.2.0"
authors = ["Michael Sproul <michael@sigmaprime.io>"]
edition = "2018"

[dependencies]
int_to_bytes = { path = "../../consensus/int_to_bytes" }
parking_lot = "0.11.0"
types = { path = "../../consensus/types" }
state_processing = { path = "../../consensus/state_processing" }
eth2_ssz = "0.1.2"
eth2_ssz_derive = "0.1.0"
serde = "1.0.116"
serde_derive = "1.0.116"
store = { path = "../store" }

[dev-dependencies]
rand = "0.7.3"
