[package]
name = "account_utils"
version = "0.1.0"
authors = ["Paul Hauner <paul@paulhauner.com>"]
edition = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = { workspace = true }
eth2_wallet = { workspace = true }
eth2_keystore = { workspace = true }
filesystem = { workspace = true }
zeroize = { workspace = true }
serde = { workspace = true }
serde_derive = "1.0.116"
serde_yaml = { workspace = true }
slog = { workspace = true }
types = { workspace = true }
validator_dir = { workspace = true }
regex = { workspace = true }
rpassword = "5.0.0"
directory = { workspace = true }
