[package]
name = "remote_signer_test"
version = "0.2.0"
authors = ["Herman Junge <herman@sigmaprime.io>"]
edition = "2018"

[dependencies]
clap = "2.33.3"
environment = { path = "../../lighthouse/environment" }
hex = "0.4.2"
httpmock = "0.5.1"
remote_signer_client = { path = "../../remote_signer/client" }
remote_signer_consumer = { path = "../../common/remote_signer_consumer" }
reqwest = { version = "0.10.8", features = ["blocking", "json"] }
serde = { version = "1.0.116", features = ["derive"] }
serde_json = "1.0.58"
tempdir = "0.3.7"
tokio = { version = "0.3.5", features = ["time"] }
types = { path = "../../consensus/types" }
tokio-compat-02 = "0.1"
