[package]
name = "eth2_testnet_config"
version = "0.1.0"
authors = ["Paul Hauner <paul@paulhauner.com>"]
edition = "2018"

build = "build.rs"

[build-dependencies]
reqwest = "0.9.20"

[dev-dependencies]
tempdir = "0.3"
reqwest = "0.9.20"

[dependencies]
serde = "1.0"
serde_yaml = "0.8"
types = { path = "../../types"}
eth2-libp2p = { path = "../../../beacon_node/eth2-libp2p"}
eth2_ssz = { path = "../ssz"}
