CONFIG_NAME: testnet
PRESET_BASE: mainnet

# Transition
# ---------------------------------------------------------------
TERMINAL_TOTAL_DIFFICULTY: 2
# By default, don't use these params
TERMINAL_BLOCK_HASH: 0x0000000000000000000000000000000000000000000000000000000000000000
TERMINAL_BLOCK_HASH_ACTIVATION_EPOCH: 18446744073709551615

# Genesis
# ---------------------------------------------------------------
# The genesis fork version looks weird for legacy reasons
MIN_GENESIS_ACTIVE_VALIDATOR_COUNT: 2
# Dec 1, 2020, 12pm UTC
MIN_GENESIS_TIME: 1606824000
GENESIS_FORK_VERSION: 0x00000ffd
# 604800 seconds (7 days)
GENESIS_DELAY: 604800

# Forking
# ---------------------------------------------------------------
# Some forks are disabled for now:
#  - These may be re-assigned to another fork-version later
#  - Temporarily set to max uint64 value: 2**64 - 1

# Altair
ALTAIR_FORK_EPOCH: 2
ALTAIR_FORK_VERSION: 0x20000090

# Merge
BELLATRIX_FORK_EPOCH: 3
BELLATRIX_FORK_VERSION: 0x20000091

# Capella
CAPELLA_FORK_EPOCH: 4
CAPELLA_FORK_VERSION: 0x20000092
MAX_WITHDRAWALS_PER_PAYLOAD: 4

# EIP4844
EIP4844_FORK_EPOCH: 5
EIP4844_FORK_VERSION: 0x20000093

# Time parameters
# ---------------------------------------------------------------
# 12 seconds
SECONDS_PER_SLOT: 12
# 14 (estimate from Eth1 mainnet)
SECONDS_PER_ETH1_BLOCK: 14
# 2**8 (= 256) epochs ~27 hours
MIN_VALIDATOR_WITHDRAWABILITY_DELAY: 256
# 2**8 (= 256) epochs ~27 hours
SHARD_COMMITTEE_PERIOD: 256
ETH1_FOLLOW_DISTANCE: 1

# Validator cycle
# ---------------------------------------------------------------
# 2**2 (= 4)
INACTIVITY_SCORE_BIAS: 4
# 2**4 (= 16)
INACTIVITY_SCORE_RECOVERY_RATE: 16
# 2**4 * 10**9 (= 16,000,000,000) Gwei
EJECTION_BALANCE: 16000000000
# 2**2 (= 4)
MIN_PER_EPOCH_CHURN_LIMIT: 4
# 2**16 (= 65,536)
CHURN_LIMIT_QUOTIENT: 65536

# Fork choice
# ---------------------------------------------------------------
# 40%
PROPOSER_SCORE_BOOST: 40

# Deposit contract
# ---------------------------------------------------------------
DEPOSIT_CONTRACT_ADDRESS: 0x4242424242424242424242424242424242424242
DEPOSIT_CHAIN_ID: 1331
DEPOSIT_NETWORK_ID: 1331

