CONFIG_NAME: testnet
PRESET_BASE: mainnet

# Genesis
# The genesis fork version looks weird for legacy reasons
GENESIS_FORK_VERSION: 0x00000ffd

# Altair
ALTAIR_FORK_EPOCH: 2
ALTAIR_FORK_VERSION: 0x20000090

# Merge
BELLATRIX_FORK_EPOCH: 3
BELLATRIX_FORK_VERSION: 0x20000091
TERMINAL_TOTAL_DIFFICULTY: 2

# Capella
CAPELLA_FORK_EPOCH: 4
CAPELLA_FORK_VERSION: 0x20000092
MAX_WITHDRAWALS_PER_PAYLOAD: 4

# EIP4844
EIP4844_FORK_EPOCH: 5
EIP4844_FORK_VERSION: 0x20000093

# Time parameters
SECONDS_PER_SLOT: 12
SLOTS_PER_EPOCH: 32

# Deposit contract
DEPOSIT_CONTRACT_ADDRESS: 0x4242424242424242424242424242424242424242

DEPOSIT_CHAIN_ID: 1331
DEPOSIT_NETWORK_ID: 1331

ETH1_FOLLOW_DISTANCE: 1
MIN_GENESIS_ACTIVE_VALIDATOR_COUNT: 2
