[package]
name = "bls"
version = "0.2.0"
authors = ["Paul Hauner <paul@paulhauner.com>"]
edition = "2018"

[dependencies]
eth2_ssz = "0.1.2"
tree_hash = "0.1.0"
milagro_bls = { git = "https://github.com/sigp/milagro_bls", tag = "v1.2.0" }
rand = "0.7.2"
serde = "1.0.102"
serde_derive = "1.0.102"
serde_utils = { path = "../../consensus/serde_utils" }
hex = "0.3"
eth2_hashing = "0.1.0"
ethereum-types = "0.9.1"
arbitrary = { version = "0.4.4", features = ["derive"], optional = true }
zeroize = { version = "1.0.0", features = ["zeroize_derive"] }
blst = { git = "https://github.com/supranational/blst.git", rev = "893d0bcf58dce17604efed6dac0c688aacc1edf7" }

[features]
default = ["supranational"]
fake_crypto = []
milagro = []
supranational = []
supranational-portable = ["supranational", "blst/portable"]
supranational-force-adx = ["supranational", "blst/force-adx"]
