[package]
name = "eth2_interop_keypairs"
version = "0.2.0"
authors = ["Paul Hauner <paul@paulhauner.com>"]
edition = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = { workspace = true }
num-bigint = "0.4.2"
ethereum_hashing = { workspace = true }
hex = { workspace = true }
serde_yaml = { workspace = true }
serde = { workspace = true }
serde_derive = "1.0.116"
bls = { workspace = true }

[dev-dependencies]
base64 = "0.13.0"
