[package]
name = "eth2_interop_keypairs"
version = "0.2.0"
authors = ["Paul Hauner <paul@paulhauner.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
num-bigint = "0.4.2"
eth2_hashing = "0.2.0"
hex = "0.4.2"
serde_yaml = "0.8.13"
serde = "1.0.116"
serde_derive = "1.0.116"
bls = { path = "../../crypto/bls" }

[dev-dependencies]
base64 = "0.13.0"
